on:
  pull_request:
    branches:
      - '**' # This pattern matches all branches

jobs:
  setup-dotnet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x' # Specify the .NET version you are using

      - name: Cache .NET packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.fsproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

  build:
    runs-on: ubuntu-latest
    needs: setup-dotnet

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Debug

  test:
    runs-on: ubuntu-latest
    needs: [setup-dotnet, build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Run tests
        run: dotnet test --no-build --verbosity normal --configuration Debug
        
  deploy:
    runs-on: ubuntu-latest
    needs: [setup-dotnet, build, test]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Publish Profile Secret
        env:
          AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        run: |
          echo "Publish profile secret:"
          echo "$AZURE_WEBAPP_PUBLISH_PROFILE"

      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v3
        with:
          app-name: "apiDeploymentTest"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}