name: CI

on:
  pull_request:
    branches:
      - '**' # This pattern matches all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run echo command
        run: echo "Hello, this is a test of the CI pipeline!"